name: honeycomb
description: A new Dart Frog application
version: 26.5.0+20
resolution: workspace
publish_to: none

environment:
  sdk: ^3.11.1

dependencies:
  core:
    path: ../../packages/core
  dart_frog: ^1.1.0

dev_dependencies:
  dart_frog_lint: ^0.1.0
  mocktail: ^1.0.3
  test: ^1.25.5
